---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: nginx restart
  service:
    name: nginx
    state: restarted

- name: gitlab runner systemd
  systemd:
    name: gitlab-runner
    enabled: yes
    state: started

