---
- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Install GitLab dependencies.
  apt: name={{ item }} update_cache=yes state=present
  loop: "{{ gitlab_modules }}"

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Install GitLab
  apt:
    name: "{{ gitlab_edition }}"
    state: present
  when: not gitlab_file.stat.exists

- name: modify prometheus
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "external_url 'http://gitlab.example.com'"
     line: "external_url 'http://gitlab.{{ virtual_domain }}'"
     backup: yes

- name: modify node_exporter
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "node_exporter['listen_address']"
     line: "node_exporter['listen_address'] = '0.0.0.0:9100'"
     backup: yes

- name: modify prometheus
  lineinfile:
     path: /etc/gitlab/gitlab.rb
     search_string: "prometheus['listen_address']"
     line: "prometheus['listen_address'] = '0.0.0.0:9090'"
     backup: yes

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: "Read an initial password"
  shell: |
    cat /etc/gitlab/initial_root_password |grep "Password:"
  register: file_content

- name: "Print the file content to a console"
  debug:
    msg: "{{ file_content.stdout }} . Use it with username root to login."
